[package]
name = "vera"
version = "0.1.1"
edition = "2024"

[dependencies]
slint = { version = "1.17.1", default-features = false, features = [
    "std",
    "compat-1-2",             # Mandatory — compile error if missing
    "renderer-software",      # CPU renderer, no GPU/OpenGL needed
    "backend-winit-wayland",  # Wayland ONLY (no X11)
] }
indexmap = "2.14.0"
webbrowser = "1.2.4"
image = { version = "0.25.10", default-features = false, features = [
    "jpeg",
    "png",
    "tiff",
    "bmp",
] }

[build-dependencies]
slint-build = { version = "1.17.1", default-features = true }
